// Generated by CoffeeScript 1.9.0
$(function() {
  var Glitchtop, g;
  Glitchtop = (function() {
    function Glitchtop() {
      this.initData();
      this.initElements();
      this.initCanvas();
      this.fillScreen();
      this.initHUD();
      this.initEvents();
      this.initAnimation();
    }

    Glitchtop.prototype.initData = function() {
      var m;
      if (m = location.href.match(/(\d+)px&H\=(\d+)-(\d+)&S=(\d+)-(\d+)&L=(\d+)-(\d+)&P=(\d)&A=(\d)$/)) {
        this.size = parseInt(m[1]);
        this.hue = {
          min: parseInt(m[2]),
          max: parseInt(m[3])
        };
        this.sat = {
          min: parseInt(m[4]),
          max: parseInt(m[5])
        };
        this.light = {
          min: parseInt(m[6]),
          max: parseInt(m[7])
        };
        this.pattern = parseInt(m[8]);
        this.animating = parseInt(m[9]);
        this.speed = 70;
      } else {
        this.size = 40;
        this.hue = {
          min: 180,
          max: 230
        };
        this.sat = {
          min: 85,
          max: 100
        };
        this.light = {
          min: 40,
          max: 80
        };
        this.pattern = 1;
        this.animating = 0;
        this.speed = 70;
      }
      return this.accent = (this.hue.max + this.hue.min) / 2;
    };

    Glitchtop.prototype.initCanvas = function() {
      this.view = {
        h: $(window).height(),
        w: $(window).width()
      };
      $("#canvas-holder").html("<canvas id=\"canvas\" width=\"" + this.view.w + "\" height=\"" + this.view.h + "\"></canvas>");
      this.canvas = document.getElementById("canvas");
      return this.ctx = this.canvas.getContext("2d");
    };

    Glitchtop.prototype.initEvents = function() {
      var count;
      this.shiftHeld = 0;
      $(document).keydown((function(_this) {
        return function(e) {
          if (e.shiftKey && !_this.shiftHeld) {
            return _this.shiftHeld = 1;
          }
        };
      })(this));
      $(document).keyup((function(_this) {
        return function(e) {
          switch (e.which) {
            case 13:
              _this.shuffle();
              break;
            case 32:
              _this.toggleAnimation();
              break;
            case 27:
              _this.toggleHUD();
          }
          if (_this.shiftHeld) {
            _this.updateData();
          }
          return _this.shiftHeld = 0;
        };
      })(this));
      $(document).mousemove((function(_this) {
        return function(e) {
          var xHue, ySat;
          if (_this.shiftHeld && (e.pageX % 5 === 1 || e.pageY % 5 === 1)) {
            xHue = ( ( e.pageX / _this.view.w ) * 360 ) | 0;
            ySat = 100 - ( ( (e.pageY / _this.view.h ) * 100 ) | 0 );
            _this.$el.sliderHue.dragslider({
              values: [xHue, xHue]
            });
            _this.$el.sliderSat.dragslider({
              values: [ySat, ySat]
            });
            _this.hue = {
              min: xHue,
              max: xHue
            };
            _this.sat = {
              min: ySat,
              max: ySat
            };
            return _this.fillScreen();
          }
        };
      })(this));
      $(document).click((function(_this) {
        return function(e) {
          if ($(e.target).closest('.hud-holder').length === 0) {
            return _this.toggleAnimation();
          }
        };
      })(this));
      count = 0;
      return $(window).resize((function(_this) {
        return function() {
          if (count % 2 === 0) {
            _this.initCanvas();
            _this.fillScreen();
          }
          return count++;
        };
      })(this));
    };

    Glitchtop.prototype.initElements = function() {
      return this.$el = {
        hudData: $('.hud-data'),
        hudHolder: $('.hud-holder'),
        shareLinkHref: $('.share-link-href'),
        shareLinkTwitter: $('.share-link-twitter'),
        sliderSize: $("#slider-size"),
        sliderHue: $("#slider-hue"),
        sliderSat: $("#slider-sat"),
        sliderLight: $("#slider-light"),
        sliderPattern: $("#slider-pattern"),
        sliderSpeed: $("#slider-speed"),
        btnAnimate: $('.btn-animate'),
        btnShuffle: $(".btn-shuffle"),
        btnCredits: $(".btn-credits"),
        btnKeyboard: $(".btn-keyboard"),
        btnShare: $(".btn-share"),
        dynamic: $('.dynamic-c'),
        btn: $('.btn')
      };
    };

    Glitchtop.prototype.initHUD = function() {
      var isQueued, that;
      isQueued = 0;
      this.$el.sliderSize.dragslider({
        value: this.size,
        rangeDrag: false,
        min: 10,
        max: 100,
        step: 10,
        slide: (function(_this) {
          return function(e, ui) {
            _this.size = ui.value;
            return _this.fillScreen();
          };
        })(this),
        change: (function(_this) {
          return function(e, ui) {
            if (!_this.shiftHeld) {
              return _this.updateData();
            }
          };
        })(this)
      });
      this.$el.sliderHue.dragslider({
        range: true,
        rangeDrag: true,
        min: 0,
        max: 360,
        values: [this.hue.min, this.hue.max],
        slide: (function(_this) {
          return function(e, ui) {
            _this.hue.min = ui.values[0];
            _this.hue.max = ui.values[1];
            return _this.fillScreen();
          };
        })(this),
        change: (function(_this) {
          return function(e, ui) {
            if (!_this.shiftHeld) {
              return _this.updateData();
            }
          };
        })(this)
      });
      this.$el.sliderSat.dragslider({
        range: true,
        rangeDrag: true,
        min: 0,
        max: 100,
        values: [this.sat.min, this.sat.max],
        slide: (function(_this) {
          return function(e, ui) {
            _this.sat.min = ui.values[0];
            _this.sat.max = ui.values[1];
            return _this.fillScreen();
          };
        })(this),
        change: (function(_this) {
          return function() {
            if (!_this.shiftHeld) {
              return _this.updateData();
            }
          };
        })(this)
      });
      this.$el.sliderLight.dragslider({
        range: true,
        rangeDrag: true,
        min: 0,
        max: 100,
        values: [this.light.min, this.light.max],
        slide: (function(_this) {
          return function(e, ui) {
            _this.light.min = ui.values[0];
            _this.light.max = ui.values[1];
            return _this.fillScreen();
          };
        })(this),
        change: (function(_this) {
          return function() {
            if (!_this.shiftHeld) {
              return _this.updateData();
            }
          };
        })(this)
      });
      this.$el.sliderSpeed.dragslider({
        value: 140 - this.speed,
        rangeDrag: false,
        min: 30,
        max: 110,
        step: 10,
        slide: (function(_this) {
          return function(e, ui) {
            _this.speed = 140 - ui.value;
            if (_this.animating != null) {
              _this.stopAnimation();
              return _this.startAnimation();
            }
          };
        })(this),
        start: (function(_this) {
          return function() {
            if (!_this.animating) {
              _this.startAnimation();
              return isQueued = 1;
            }
          };
        })(this),
        stop: (function(_this) {
          return function() {
            if (_this.animating && isQueued) {
              _this.stopAnimation();
              return isQueued = 0;
            }
          };
        })(this)
      });
      this.$el.sliderPattern.dragslider({
        value: this.pattern,
        rangeDrag: false,
        min: 1,
        max: 4,
        step: 1,
        slide: (function(_this) {
          return function(e, ui) {
            _this.pattern = ui.value;
            return _this.fillScreen();
          };
        })(this),
        change: (function(_this) {
          return function(e, ui) {
            return _this.updateData();
          };
        })(this)
      });
      this.$el.btnAnimate.click((function(_this) {
        return function(e) {
          _this.toggleAnimation();
          return e.stopPropagation();
        };
      })(this));
      that = this;
      this.$el.btnShuffle.click(function(e) {
        that.shuffle();
        $(this).css({
          color: "hsl(" + this.accent + ", 80%, 70%)"
        });
        return e.stopPropagation();
      });
      this.$el.btnCredits.click((function(_this) {
        return function(e) {
          _this.toggleVisibility('credits');
          return e.stopPropagation();
        };
      })(this));
      this.$el.btnKeyboard.click((function(_this) {
        return function(e) {
          _this.toggleVisibility('keyboard');
          return e.stopPropagation();
        };
      })(this));
      this.$el.btnShare.click((function(_this) {
        return function(e) {
          _this.toggleVisibility('share');
          return e.stopPropagation();
        };
      })(this));
      return this.$el.btn.hover(function() {
        $(this).addClass("dynamic-c").css({
          color: "hsl(" + this.accent + ", 80%, 70%)"
        });
        return true;
      }, function() {
        var $this, el;
        $this = $(this);
        el = $this.attr("class").split(" ")[1].split("-")[1];
        if (!$("." + el).is(":visible")) {
          $this.removeClass("dynamic-c");
          $this.css({
            color: "rgb(200,200,200)"
          });
        }
        return true;
      });
    };

    Glitchtop.prototype.initAnimation = function() {
      if (this.animating) {
        return this.startAnimation;
      }
    };

    Glitchtop.prototype.startAnimation = function() {
      this.animating = 1;
      this.animatingInt = setInterval((function(_this) {
        return function() {
          _this.fillScreen();
          return true;
        };
      })(this), this.speed);
      return this.$el.btnAnimate.html('<i class="icon-pause"></i>');
    };

    Glitchtop.prototype.stopAnimation = function() {
      this.animating = 0;
      try {
        clearInterval(this.animatingInt);
      } catch (_error) {}
      return this.$el.btnAnimate.html('<i class="icon-play"></i>');
    };

    Glitchtop.prototype.toggleAnimation = function() {
      if (this.animating) {
        this.stopAnimation();
      } else {
        this.startAnimation();
      }
      return this.updateData();
    };

    Glitchtop.prototype.fillScreen = function() {
      if (this.size < 20) {
        this.draw(4);
      } else if (this.size < 50) {
        this.draw(2);
      } else {
        this.draw(1);
      }
      this.dataToUI();
      return this.changeUIColor();
    };

    Glitchtop.prototype.draw = function(d) {
      var h, s, w;
      d = d * this.pattern;
      s = this.size;
      w = Math.floor(this.view.w / this.size);
      h = Math.floor(this.view.h / this.size);
      w = Math.floor(w / d) + 1;
      h = Math.floor(h / d) + 1;
      for ( var x = 0; x < w; x++ ) {
				for ( var y = 0; y < h; y++ ) {
					this.ctx.fillStyle = this.genColor();
					for ( var a = (d-1); a >= 0; a-- ) {
						for ( var b = (d-1); b >= 0; b-- ) {
							this.ctx.fillRect( (x+w*a)*s, (y+h*b)*s, s, s);
						}
					}
				}
			};
      return true;
    };

    Glitchtop.prototype.shuffle = function() {
      this.randomize();
      this.updateData();
      this.updateHUD();
      return this.fillScreen();
    };

    Glitchtop.prototype.randomize = function() {
      var _ref, _ref1, _ref2;
      this.size = Math.round(this.rand(10, 100) / 10) * 10;
      this.hue = {
        min: this.rand(0, 360),
        max: this.rand(0, 360)
      };
      if (this.hue.max < this.hue.min) {
        _ref = [this.hue.max, this.hue.min], this.hue.min = _ref[0], this.hue.max = _ref[1];
      }
      this.sat = {
        min: this.rand(40, 80),
        max: this.rand(60, 100)
      };
      if (this.sat.max < this.sat.min) {
        _ref1 = [this.sat.max, this.sat.min], this.sat.min = _ref1[0], this.sat.max = _ref1[1];
      }
      this.light = {
        min: this.rand(20, 60),
        max: this.rand(40, 100)
      };
      if (this.light.max < this.light.min) {
        return _ref2 = [this.light.max, this.light.min], this.light.min = _ref2[0], this.light.max = _ref2[1], _ref2;
      }
    };

    Glitchtop.prototype.deviceCheck = function() {
      if (navigator.userAgent.match(/iPhone/i)) {
        this.$el.hudHolder.remove();
        true;
      }
      return false;
    };

    Glitchtop.prototype.toggleVisibility = function(cl) {
      var $el;
      $el = $('.' + cl);
      if ($el.is(":visible")) {
        $el.hide();
      } else {
        $('.info').hide();
        $el.show();
      }
      this.$el.btn.removeClass('dynamic-c').css({
        color: 'rgb(200,200,200)'
      });
      return $('.btn-' + cl).addClass('dynamic-c').css({
        color: "hsl(" + this.accent + ", 80%, 70%)"
      });
    };

    Glitchtop.prototype.toggleHUD = function() {
      var $hud;
      $hud = this.$el.hudHolder;
      if ($hud.is(':visible')) {
        return $hud.hide();
      } else {
        return $hud.show();
      }
    };

    Glitchtop.prototype.changeUIColor = function() {
      this.accent = (this.hue.min + this.hue.max) / 2;
      return this.$el.dynamic.css({
        color: "hsl(" + this.accent + ", 80%, 70%)"
      });
    };

    Glitchtop.prototype.genColor = function(hue, sat, light) {
      var h, l, s;
      h = hue != null ? hue : this.rand(this.hue.min, this.hue.max);
      s = sat != null ? sat : this.rand(this.sat.min, this.sat.max);
      l = light != null ? light : this.rand(this.light.min, this.light.max);
      return "hsl(" + h + "," + s + "%," + l + "%)";
    };

    Glitchtop.prototype.updateData = function() {
      this.dataToURL();
      return this.dataToUI();
    };

    Glitchtop.prototype.dataToURL = function() {
      return location.hash = this.toHash();
    };

    Glitchtop.prototype.dataToUI = function() {
      var link;
      link = location.href;
      this.$el.hudData.html(this.toStr());
      this.$el.shareLinkHref.attr('href', link);
      return this.$el.shareLinkTwitter.attr('href', "http://twitter.com/home?status=I made this with %23glitchtop " + encodeURIComponent(link));
    };

    Glitchtop.prototype.updateHUD = function() {
      this.$el.sliderSize.dragslider({
        value: this.size
      });
      this.$el.sliderHue.dragslider({
        values: [this.hue.min, this.hue.max]
      });
      this.$el.sliderSat.dragslider({
        values: [this.sat.min, this.sat.max]
      });
      return this.$el.sliderLight.dragslider({
        values: [this.light.min, this.light.max]
      });
    };

    Glitchtop.prototype.toHash = function() {
      return this.size + "px&H=" + this.hue.min + "-" + this.hue.max + "&S=" + this.sat.min + "-" + this.sat.max + "&L=" + this.light.min + "-" + this.light.max + "&P=" + this.pattern + "&A=" + this.animating;
    };

    Glitchtop.prototype.toStr = function() {
      return this.size + "px, H=" + this.hue.min + "-" + this.hue.max + ", S=" + this.sat.min + "-" + this.sat.max + ", L=" + this.light.min + "-" + this.light.max;
    };

    Glitchtop.prototype.rand = function(min, max) {
      return Math.floor(Math.random() * (max - min + 1)) + min;
    };

    return Glitchtop;

  })();
  return g = new Glitchtop;
});
